version: '3'

services:
  application:
    image: express42/future-devops
    build: .
    environment:
    - REDIS_HOST=redis
    volumes:
    - ./future-devops:/usr/src/app
    depends_on:
    - redis
  celery-worker:
    image: express42/future-devops
    build: .
    command: celery -A tasks worker --loglevel=info
    environment:
    - REDIS_HOST=redis
    volumes:
    - ./future-devops:/usr/src/app
    depends_on:
    - redis
  redis:
    image: redis:alpine
  nginx:
    image: nginx:alpine
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf:ro
    - ./static:/static:ro
    ports:
    - 8080:80
    depends_on:
    - application