version: '3'

services:
  future-devops:
    build: .
    ports:
    - 8080:80
    volumes:
    - ./future-devops:/future-devops
    - ./static:/static
    - ./default.conf:/etc/nginx/conf.d/default.conf